server:
  port: 8088   # 已有配置

spring:
  # MySQL 配置
  datasource:
    url: jdbc:mysql://mysql1:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: JFCHArjYAN74kBbdFNQQ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10

